name: expandable_datatable
description: A flutter package for viewing and editing data in a table view with expandable rows.
version: 0.0.8+4
publish_to: none
# repository: https://github.com/ismailyegnr/expandable_datatable
# issue_tracker: https://github.com/ismailyegnr/expandable_datatable/issues
# homepage: https://github.com/ismailyegnr/expandable_datatable

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.0.0
